language: node_js
node_js:
  - "8.1.2"

branches:
  only:
    - master
    - /^greenkeeper/.*$/

cache:
  directories:
    - node_modules
    
before_script:
  - npm install -g @angular/cli

script:
  - ng build --prod